# Generated by Django 4.2.2 on 2023-06-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartSneakers',
        ),
    ]
